language: node_js
node_js:
  - '10'
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  repo: arthur-nesterenko/arthur.nesterenko.github.io
  local_dir: ./public
